spring:
  datasource:
    url: jdbc:mysql://database-1.c8rqqx6xupu3.us-east-2.rds.amazonaws.com:3306/movies?useUnicode=true&characterEncoding=utf8&useSSL=false&relaxAutoCommit=true
    username: admin
    password: magicoftheMoment37
    driver-class-name: com.mysql.jdbc.Driver
    max-pool-size: 5

youtube:
  api:
    key: AIzaSyBERRsW1tvyhIFH4FaTbzwF5BETUq0ojpQ